In [1]:
import numpy as np

def primesfrom2to(n):
    # http://stackoverflow.com/questions/2068372/fastest-way-to-list-all-primes-below-n-in-python/3035188#3035188
    """ Input n>=6, Returns a array of primes, 2 <= p < n """
    sieve = np.ones(n/3 + (n%6==2), dtype=np.bool)
    sieve[0] = False
    for i in range(int(n**0.5)//3+1):
        if sieve[i]:
            k=3*i+1|1
            sieve[      ((k*k)/3)      ::2*k] = False
            sieve[(k*k+4*k-2*k*(i&1))/3::2*k] = False
    return np.r_[2,3,((3*np.nonzero(sieve)[0]+1)|1)]

In [2]:
def power_count(n,p):
    res = 0
    while n%p == 0:
        n //= p
        res += 1
    return res

In [3]:
from math import sqrt
def factorize(n):
    pfs = primesfrom2to(n//2+1)
    pc = np.frompyfunc(power_count,2,1,dtype = np.int32)
    
    ct = pc(n,pfs)
    index = np.where(ct>0)
    return np.stack((pfs[index],ct[index]))

factorize(19391400)   

D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\numpy\core\numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\ipykernel\__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


array([[2, 3, 5, 7, 19],
       [3, 6, 2, 1, 1]], dtype=object)

In [4]:
from sympy import primefactors

In [5]:
primefactors(2**3*3**4*5**2*1197)

[2, 3, 5, 7, 19]

In [6]:
2**3*3**4*5**2*1197

19391400

In [7]:
prms = factorize(19391400)[0]
cts = factorize(19391400)[1]
t=prms**cts

D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\numpy\core\numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\ipykernel\__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
D:\WinPython\WinPython-32bit-3.5.2.3Qt5\python-3.5.2\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [8]:
np.multiply.reduce(t)

19391400

In [34]:
def proper_divsors(x):
    r= np.arange(2,int(sqrt(x)+1))
    c = np.mod(x,r)
    z = np.logical_xor(r,c)
    sd = r[z]
    bd = x//sd
    res = np.r_[1,sd,bd]
    res.sort()
    return  res

proper_divsors(3000)

array([   1,    2,    3,    4,    5,    6,    8,   10,   12,   15,   20,
         24,   25,   30,   40,   50,   60,   75,  100,  120,  125,  150,
        200,  250,  300,  375,  500,  600,  750, 1000, 1500])

In [36]:
divisors_np(3000)

array([   1,    2,    3,    4,    5,    6,    8,   10,   12,   15,   20,
         24,   25,   30,   40,   50,   60,   75,  100,  120,  125,  150,
        200,  250,  300,  375,  500,  600,  750, 1000, 1500, 3000])

In [22]:
def divisors_np(n):
    candidates = np.arange(1,sqrt(n) +1,dtype = int)
    div = np.mod(n,candidates)
    index = np.where(div ==0)
    small_divs = candidates[index]
    big_divs = n//small_divs
    res = np.r_[small_divs,big_divs]
    res.sort()
    return res

In [23]:
divisors_np(313800)
print(len(divisors_np(313800)))

48


In [24]:
from sympy import divisors

In [25]:
len(divisors(313800))

48

In [26]:
%%timeit
divisors_np(3138000)

The slowest run took 5.17 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 48.4 µs per loop


In [27]:
%%timeit
divisors(3138000)

10000 loops, best of 3: 60.9 µs per loop


In [28]:
divisors_np(3138000)

array([      1,       2,       3,       4,       5,       6,       8,
            10,      12,      15,      16,      20,      24,      25,
            30,      40,      48,      50,      60,      75,      80,
           100,     120,     125,     150,     200,     240,     250,
           300,     375,     400,     500,     523,     600,     750,
          1000,    1046,    1200,    1500,    1569,    2000,    2092,
          2615,    3000,    3138,    4184,    5230,    6000,    6276,
          7845,    8368,   10460,   12552,   13075,   15690,   20920,
         25104,   26150,   31380,   39225,   41840,   52300,   62760,
         65375,   78450,  104600,  125520,  130750,  156900,  196125,
        209200,  261500,  313800,  392250,  523000,  627600,  784500,
       1046000, 1569000, 3138000])