## PEP16
2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

###   Pure Python

In [1]:
print( sum(map(int, str(2 ** 1000))))

1366


In [2]:
%%timeit
sum(map(int, str(2 ** 1000)))

10000 loops, best of 3: 64.1 µs per loop


### numpy version

In [3]:
import numpy as np

def pow2(k):
    x = np.array([0]*k+[1]) # initialize [0,0,0,...,1]
    for i in range(0,k):
        temp = x*2//10       
        push = np.zeros(k+1,dtype = np.uint32) 
        push[0:k] = temp[1:k+1] ## 找出要进位的位置 
        x =  x*2%10
        x = x+push  # 进位前移
    return x

from time import clock
start = clock()
print(pow2(1000).sum())
end = clock()
print("time cost %f" %(end- start))

1366
time cost 0.088323


In [4]:
pow2(22)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 9, 4, 3, 0, 4], dtype=int64)

In [5]:
pow2(50)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 5, 8, 9, 9, 9, 0, 6, 8,
       4, 2, 6, 2, 4], dtype=int64)

***
***
## PEP18

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3

7 4

2 4 6

8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75

95 64

17 47 82

18 35 87 10

20 04 82 47 65

19 01 23 75 03 34

88 02 77 73 07 63 67

99 65 04 28 06 16 70 92

41 41 26 56 83 40 80 70 33

41 48 72 33 47 32 37 16 94 29

53 71 44 65 25 43 91 52 97 51 14

70 11 33 28 77 73 17 78 39 68 17 57

91 71 52 38 17 14 91 43 58 50 27 29 48

63 66 04 68 89 53 67 30 73 16 69 87 40 31

04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

### python + numpy version

In [5]:
from io import StringIO
lst =[]
f = open("PEP18.txt")
for line in f.readlines():
    c = StringIO(line)
    a = np.loadtxt(c,dtype = np.int32)
    lst.append(a.tolist())
    
lst

[75,
 [95, 64],
 [17, 47, 82],
 [18, 35, 87, 10],
 [20, 4, 82, 47, 65],
 [19, 1, 23, 75, 3, 34],
 [88, 2, 77, 73, 7, 63, 67],
 [99, 65, 4, 28, 6, 16, 70, 92],
 [41, 41, 26, 56, 83, 40, 80, 70, 33],
 [41, 48, 72, 33, 47, 32, 37, 16, 94, 29],
 [53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14],
 [70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57],
 [91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48],
 [63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31],
 [4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]]

In [6]:
for i in range(13,0,-1):
    for j in range(0,len(lst[i])):
        lst[i][j] = lst[i][j]+max(lst[i+1][j],lst[i+1][j+1])
print(lst)

[75, [995, 999], [818, 900, 935], [704, 801, 853, 792], [686, 640, 766, 731, 782], [666, 614, 636, 684, 660, 717], [647, 501, 613, 609, 533, 657, 683], [559, 499, 479, 536, 514, 526, 594, 616], [460, 434, 419, 475, 508, 470, 510, 524, 487], [419, 365, 393, 387, 419, 425, 430, 376, 454, 322], [378, 317, 231, 321, 354, 372, 393, 354, 360, 293, 247], [325, 246, 187, 178, 256, 329, 273, 302, 263, 242, 193, 233], [255, 235, 154, 150, 140, 179, 256, 209, 224, 172, 174, 176, 148], [125, 164, 102, 95, 112, 123, 165, 128, 166, 109, 122, 147, 100, 54], [4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]]


In [7]:
75+999

1074

## PEP20

In [8]:
from math import factorial
sum([int(i) for i in str(factorial(100))])

648

## PEP21

In [20]:
def pds(n):
    if n<=1:
        return 0
    if n==2:
        return 1
    """return sum of proper divisor of n"""
    res =1
    for i in range(2,int(n**.5)+1):
        if n%i ==0:
            res += i
            res += n//i
    return res

In [21]:
pds(220)

284

In [22]:
total = 0
for i in range(2,100000):
    a = pds(i)
    if pds(a)==i and a!= i:
        print(i)
        total +=i
print("answer:",total)

220
284
1184
1210
2620
2924
5020
5564
6232
6368
10744
10856
12285
14595
17296
18416
63020
66928
66992
67095
69615
71145
76084
79750
87633
88730
answer: 852810


## Numpy Python

In [37]:
def prop_div(n):
    nums = np.arange(1,n//2+1)
    div = np.mod(n,nums)
    return nums[div==0]

In [38]:
def pds_np(n):
    return prop_div(n).sum()

In [39]:
prop_div(220)

array([  1,   2,   4,   5,  10,  11,  20,  22,  44,  55, 110])

In [40]:
pds_np(220)

284

In [41]:
pairs = [[i,i] for i in range(1,10001)]
pn = np.array(pairs,dtype = np.int32)

In [42]:
sumpd = np.frompyfunc(pds_np,1,1)

In [43]:
pn[::,1] = sumpd(pn[::,1])
pn

array([[    1,     0],
       [    2,     1],
       [    3,     1],
       ..., 
       [ 9998,  5002],
       [ 9999,  5913],
       [10000, 14211]])

In [44]:
im1 = []
for k in pn:
    x ,y = k
    im1.append(x+y*1j)

In [45]:
pairs = [[i,i] for i in range(1,10001)]
rpn = np.array(pairs,dtype = np.int32)
rpn[::,0] = sumpd(pn[::,0])
rpn

array([[    0,     1],
       [    1,     2],
       [    1,     3],
       ..., 
       [ 5002,  9998],
       [ 5913,  9999],
       [14211, 10000]])

In [46]:
im2 = []
for k in rpn:
    x ,y = k
    im2.append(x+y*1j)

In [47]:
total = 0
for item in im1:
    if item in im2:
        if item.real != item.imag:
            total += item
            print(item)
print(total)

(220+284j)
(284+220j)
(1184+1210j)
(1210+1184j)
(2620+2924j)
(2924+2620j)
(5020+5564j)
(5564+5020j)
(6232+6368j)
(6368+6232j)
(31626+31626j)
